### ISSUE TITLE
游戏行业使用咨询

### ISSUE THREAD

**Issue by baodingfengyun** [lealone/Lealone#100]
目前是在做出海类的轻度游戏（全球同服），特点是不停服维护，所以数据库的选择非常重要。我是作为项目服务端负责。当前的数据库采用的是MongoDB，但是因为横向扩展的问题，新的项目考虑过Cassandra。不过看到Lealone后，觉得易用方面更好。从扩展和易用方面，Leanlone比C* 更合适我的场景吗？

**Comment by codefollower** [comment]
如果这个游戏项目没有事务要求，Cassandra会更好一些，Lealone比较适合有事务要求的OLTP场景。
不过Lealone目前还没有GA，所以我还不建议用于生产环境，至少还得3个月才能满足生产环境的要求，当前的工作一直在修bug，增强系统稳定性。

所以如果您的项目比较急，推荐您考虑其他技术方案先，谢谢关注Lealone。

**Comment by baodingfengyun** [comment]
> 如果这个游戏项目没有事务要求，Cassandra会更好一些，Lealone比较适合有事务要求的OLTP场景。
> 不过Lealone目前还没有GA，所以我还不建议用于生产环境，至少还得3个月才能满足生产环境的要求，当前的工作一直在修bug，增强系统稳定性。
> 
> 所以如果您的项目比较急，推荐您考虑其他技术方案先，谢谢关注Lealone。

感谢快速回复. 游戏业务会同时使用支持事务的部分和落地存储的部分.

**Comment by codefollower** [comment]
我这边的同事之前也有用MongoDB做游戏项目，不过可能因为用户量不是很大，所以还是能支撑的。游戏项目对并发要求比较高，也属于OLTP场景，所以也是Lealone的应用场景之一，只能等3个月后再看看了。

我们自己也有两个互联网项目正在用Lealone来做，把自己当小白鼠先，其他人我还不推荐使用，Lealone还不稳定，出了问题我们比较懂源代码，能及时修复，对于其他人我怕影响到别人的业务，所以还是请您稳妥先吧。

**Comment by baodingfengyun** [comment]
恩. 不过Lealone+Vert.x做互联网项目肯定是非常好的. 再次感谢回复.
