### ISSUE TITLE
这里好像有bug 没有 throw

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#102]
https://github.com/lealone/Lealone/blob/82665ed9e24245ae85a6561b04bd65620ced2107/lealone-common/src/main/java/org/lealone/common/compress/LZFInputStream.java#L60

**Comment by igoso** [comment]
it's not a bug . see : https://github.com/lealone/Lealone/blob/82665ed9e24245ae85a6561b04bd65620ced2107/lealone-common/src/main/java/org/lealone/common/exceptions/DbException.java#L344

**Comment by codefollower** [comment]
谢谢，bug已修复
