### ISSUE TITLE
sharding模式下新建表异常？

### ISSUE THREAD

**Issue by duzeng** [lealone/Lealone#113]
![image](https://user-images.githubusercontent.com/13018851/120495030-e6fe7280-c3ee-11eb-9aa6-d2256f90be90.png)

![image](https://user-images.githubusercontent.com/13018851/120494873-c6361d00-c3ee-11eb-97fb-d02f4ce431e2.png)

**Comment by codefollower** [comment]
最近改动太多，sharding模式下的测试用例还未跑过，我明天看看。
最近的5.0版本只专注于单机模式和复制集群模式的稳定性，sharding集群模式要稳定得推迟到5.1了。

**Comment by codefollower** [comment]
@duzeng 你更新一下最新代码，然后用 build -p 打包
我试了一下可以建表了，不过 sharding 集群模式目前还不是很稳定，可能还有不少 bug
