### ISSUE TITLE
这个地方名称不知道能不能改

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#116]
https://github.com/lealone/Lealone/blob/3ac0c3ecd1ea4222d4fe973d83cab71c8ad4c305/lealone-client/src/main/java/org/lealone/client/jdbc/JdbcDatabaseMetaData.java#L67

还有下面的
getDriverName

**Comment by codefollower** [comment]
可以，JDBC 客户端的代码很多还是直接复用 H2 的，有的输出中包含H2的遗漏了。

**Comment by qqcbqqkcel** [comment]
h2这个是真的好多问题，我学习时。看到好多代码互相依赖，父子依赖。头多大了.

**Comment by codefollower** [comment]
H2 不分模块的，所有代码全搞在一起，当年我为了重构它也累坏了。

**Comment by codefollower** [comment]
如果你看 Lealone 的代码，版权声明中有 Copyright 2004-2014 H2 Group. Multiple-Licensed under the MPL 2.0,
那都是 H2 的代码，如果这些代码中没有在后面加上@author zhh，那么大多是没有什么改动的。

**Comment by qqcbqqkcel** [comment]
> 如果你看 Lealone 的代码，版权声明中有 Copyright 2004-2014 H2 Group. Multiple-Licensed under the MPL 2.0,
> 那都是 H2 的代码，如果这些代码中没有在后面加上@author zhh，那么大多是没有什么改动的。

好的，谢谢。我去捉h2的bug
