### ISSUE TITLE
重写方法缺少 @Override 注解

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#117]
用 IDEA 分析了一下，一以下几个类好多重写方法缺少 @Override 注解
AutoCloseInputStream
CompressDeflate
CompressLZF
CompressNo
DbObjectTestBase
IntIntHashMap
LZFOutputStream
MathUtils
SecureFileStorage
Task

**Comment by codefollower** [comment]
这些没什么影响的，没有加@override的地方基本上是从H2那里继承来的代码而且没有改过。
我用的是Eclipse，代码修改保存后会自动加@override。

**Comment by qqcbqqkcel** [comment]
> 这些没什么影响的，没有加@override的地方基本上是从H2那里继承来的代码而且没有改过。
> 我用的是Eclipse，代码修改保存后会自动加@override。
嗯。是没什么影响，就是看着不舒服哈
