### ISSUE TITLE
字段多次赋值，插入是第一次的值

### ISSUE THREAD

**Issue by jiayaoguang** [lealone/Lealone#118]
rowId2 = u.id.set(2000).name.set("1").name.set("Rob1").notes.set("notes2").insert();
name 预期结果是 Rob1 实际结果是 1
产生原因 NVPair 放进 Set 不会替换旧数据，请问就是这么设计的吗

**Comment by codefollower** [comment]
原先使用了一个HashSet来存，导致后面的无法覆盖前面的，我换成HashMap修复一下，感谢报告bug。
