### ISSUE TITLE
客户端的 TcpClientConnection 不需要保存 session 吧

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#120]
https://github.com/lealone/Lealone/blob/4b6138ed2328e1ea750e6467f73575d02c376f3e/lealone-net/src/main/java/org/lealone/net/TcpClientConnection.java#L26

客户端创建 session 直接返回了，不需要保存在 sessions 中吧
项目里面没有看到有地方调用了如下代码，所以 sessions 永远为空。
public void addSession(int sessionId, Session session) {
    sessions.put(sessionId, session);
}

**Comment by codefollower** [comment]
暂时没用到，后续完善运行模式变更场景会用到，用于接收后端数据库推送过来的信息，动态修改 session 的状态。
你搜一下 getSession 哪里有调用就知道了。

removeSession 那里也有个注释，原先是想根据 sessions.isEmpty() 来关闭 TCP 连接，但是会引起问题，所以就暂时不调用 addSession 了。

**Comment by qqcbqqkcel** [comment]
明白了，那没问题了。
