### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ronin0079** [lealone/Lealone#121]
https://github.com/lealone/Lealone/blob/2fa46d5e78dba07b0c6848ee5a699f3d543fc8ff/lealone-orm/src/main/java/org/lealone/orm/Model.java#L729

set在!areEqual时有效，那么update相同值时nvPairs会等于null

        if (whereExpressionBuilder != null)
            update.setCondition(whereExpressionBuilder.getExpression());
        if(nvPairs!=null)
            for (NVPair p : nvPairs.values()) {
                update.setAssignment(dbTable.getColumn(p.name), ValueExpression.get(p.value));
            }

**Comment by codefollower** [comment]
多谢报告bug，已经修复
