### ISSUE TITLE
修改事务隔离级别后 异常

### ISSUE THREAD

**Issue by qeemin** [lealone/Lealone#129]
代码中默认事务隔离级别修改为 Connection.TRANSACTION_REPEATABLE_READ,并重新编译启动 插入的数据无法查询出来
![image](https://user-images.githubusercontent.com/50012657/145704778-ccbe86f1-8000-4a7b-b703-b946826ad7fd.png)

**Comment by codefollower** [comment]
这周新加的代码引入了新 bug，
请更新一下代码，已经修复了。

在 sql 命令行窗口修改事务隔离级别可以用以下命令：
set transaction_isolation_level repeatable_read;
或直接用数字：
set transaction_isolation_level 4;

手动提交事务：set AUTOCOMMIT false;

禁用语句缓存: set QUERY_CACHE_SIZE 0;

感谢报告问题。
