### ISSUE TITLE
编译build.bat -i 异常  java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by fqtyfz** [lealone/Lealone#130]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:2.4:jar (attach-sources) on project lealone: Execution attach-sources of goal org.apache.maven.plugins:maven-source-plugin:2.4:jar failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-source-plugin:2.4:jar: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-source-plugin:2.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : Index 1 out of bounds for length 1

olap模块中<source>16</source>，不再支持jdk1.8了吗？

**Comment by fqtyfz** [comment]
maven-resources-plugin  组件版本用3.2.0，相应的其它也升一下，就好了

**Comment by codefollower** [comment]
直接装个 jdk 17 就可以了，
我现在用 jdk 17 作为日常开发，然后再把 lealone 编译打包到 jdk 1.8 的版本。

lealone-olap 模块用了 jdk.incubator.vector，所以至少需要 jdk 16。
这个模块比较新，如果不想装 jdk 新版本，在 pom.xml 文件里把 <module>lealone-olap</module> 注释掉就可以了。
