### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [lealone/Lealone#140]
Hey there!

I belong to an open source security research community, and a member (@fturan0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by codefollower** [comment]
Email Contact
codefollower AT gmail.com

**Comment by JamieSlome** [comment]
@codefollower - thank you for your response.

Just for reference, you can view the report directly here:

https://huntr.dev/bounties/67fec76a-ddd9-4fec-b72d-53fd9601771c/

**Comment by JamieSlome** [comment]
E-mail sent as well! ❤️

**Comment by codefollower** [comment]
@JamieSlome
Thanks

JdbcUtils.getConnection is legacy code of h2, lealone not use the method, i will remove it.

**Comment by JamieSlome** [comment]
@codefollower - thanks for your follow-up!

If you could approve/reject the vulnerability, and confirm the fix, that would be much appreciated! ❤️
