### ISSUE TITLE
maven-source-plugin

### ISSUE THREAD

**Issue by HUANGLIURU** [lealone/Lealone#151]
https://github.com/lealone/Lealone/blob/e2e8936a07dd42cdda867c973bcc0297168f9d3e/pom.xml#L99
不知道是不是我电脑环境原因，必须3.2.1才能打包

**Comment by codefollower** [comment]
apache maven 的版本可能会影响具体的插件，我用的是 apache-maven-3.8.1，在 jdk 1.8 和 jdk 17 都是可以正常打包的。
如果只是你的个人环境，那你就改成3.2.1就好了。这个插件目前没有考虑升级版本。

**Comment by HUANGLIURU** [comment]
> apache maven 的版本可能会影响具体的插件，我用的是 apache-maven-3.8.1，在 jdk 1.8 和 jdk 17 都是可以正常打包的。 如果只是你的个人环境，那你就改成3.2.1就好了。这个插件目前没有考虑升级版本。

好的，谢谢。我用的maven-3.8.2

**Comment by zhoujin7** [comment]
> > apache maven 的版本可能会影响具体的插件，我用的是 apache-maven-3.8.1，在 jdk 1.8 和 jdk 17 都是可以正常打包的。 如果只是你的个人环境，那你就改成3.2.1就好了。这个插件目前没有考虑升级版本。
> 
> 好的，谢谢。我用的maven-3.8.2

要用maven 3.8.1
