### ISSUE TITLE
idea打开项目后，编译报错

### ISSUE THREAD

**Issue by zhangyou1010** [lealone/Lealone#153]
idea打开项目后，编译报错：无效的标记: --release

**Comment by codefollower** [comment]
是不是 idea 不支持 maven-compiler-plugin 的 `<release>8</release>`

**Comment by norvid** [comment]
与idea无关。是jdk的问题。<release>标注是jdk9以后才支持。之前的jdk包括广泛使用的jdk8是不认识<release>的。所以执行mvn编译时会报错。对于jdk8的环境，删掉根目录下的 pom.xml 中的两处 <release>8</release> 后，重新执行mvn编码可以通过。
这个issue关闭吧。

**Comment by codefollower** [comment]
> 与idea无关。是jdk的问题。标注是jdk9以后才支持。之前的jdk包括广泛使用的jdk8是不认识的。所以执行mvn编译时会报错。对于jdk8的环境，删掉根目录下的 pom.xml 中的两处 8 后，重新执行mvn编码可以通过。 这个issue关闭吧。
[从源码构建Lealone](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BB%8E%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BALealone.md)
用 maven 构建 lealone 推荐用 jdk 17，加上 `<release>8</release>` 就能在 jdk 1.8 下运行了，直接用 jdk 1.8 相关于 javac --release 8，所以就编译出错了，java 1.8 不支持 --release 8

**Comment by codefollower** [comment]
[从源码构建Lealone](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BB%8E%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BALealone.md)
用 maven 构建 lealone 推荐用 jdk 17，加上 `<release>8</release>` 就能在 jdk 1.8 下运行了，直接用 jdk 1.8 相关于 javac --release 8，所以就编译出错了，java 1.8 不支持 --release 8
