### ISSUE TITLE
Unrecognized parameters: [REPLICATION_FACTOR]

### ISSUE THREAD

**Issue by beijingcn** [lealone/Lealone#155]
General error: "org.lealone.common.exceptions.ConfigException: Unrecognized parameters: [REPLICATION_FACTOR] for database MYDB_REPLICATION,

**Comment by beijingcn** [comment]
执行 CREATE DATABASE mydb_replication RUN MODE replication PARAMETERS(replication_factor: 2); 报以上错误

**Comment by codefollower** [comment]
lealone 5.0 现在只专注单机版，不支持复制模式了。
