### ISSUE TITLE
sharding   模式  limit 无效

### ISSUE THREAD

**Issue by beijingcn** [lealone/Lealone#157]
<img width="709" alt="limit" src="https://user-images.githubusercontent.com/11664820/192091165-9cdb6535-2572-4d9a-aaf1-aad044756c88.png">

如图

**Comment by codefollower** [comment]
1. 你是用自己构建出的 lealone 5.0 来创建 sharding 模式的数据库？
2. 还是下我打包的 https://github.com/lealone/Lealone-Docs/releases/download/lealone-docs-1.0.0/lealone-5.0.0.jar

如果是1的话，lealone 5.0 只是个单机版本，不支持复制模式和 sharding 模式的数据库的，
如果是2的话，那个是我4月份打的 jar 包，虽然支持复制模式和 sharding 模式，但只是个实验版，所以有 bug。

从5月份开始，复制模式和 sharding 模式的功能已经不开源了。

**Comment by codefollower** [comment]
截图右边的三张表说明 lealone 的代码是老的，新的代码改了，第一张表没有了，第三张表 table_alter_history 已近归属到 INFORMATION_SCHEMA，public 是用户创建的表默认的 SCHEMA，INFORMATION_SCHEMA 是 lealone 内部使用的 SCHEMA

最好更新一下 lealone 5.0 的代码，如果在最新的 lealone 5.0 中测试，我没有测出问题。
