### ISSUE TITLE
添加CLOB字段后现有的数据查询不出来

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#161]
alter table DEFINE
    add FORM_VALUE CLOB;

执行添加字段，查询数据报
```java
[2022-09-28 20:40:50] [HY000][50000] General error: "java.lang.ArrayIndexOutOfBoundsException: 19"; SQL statement:
[2022-09-28 20:40:50] SELECT t.*
[2022-09-28 20:40:50] FROM "PUBLIC".INSTANCE t [50000-0]

```
把数据全部删除后再添加是可以的。

**Comment by codefollower** [comment]
是你的客户端连了名为 lealone 的数据库，然后在里面建表增加新字段吧，
lealone 这个数据库是系统数据库，我原本的设计是不给普通用户在里面建表的，只给系统使用，系统设计的表是不会修改表结构的，所以就没有 table_alter_history 这个系统表，有了这个表新加字段时就在里面登记，然后现有的老记录读这个表就会构建出新的字段值，如果没有这个表，当使用 select * from t 时，字段变成3个了，但是原有的老记录还是两个字段，所以就抛异常了。

总之，业务系统不建议直接在 lealone 这个系统数据库里面存放业务的任何数据，这个 lealone 数据库只给系统用，以后随时会改。

你用 create database xxx 创建新的数据库即可，新创建的数据库默认用户名也是 root 密码也是空。

**Comment by qqcbqqkcel** [comment]
我确实是用的 lealone 但是最好提醒一下，要不然后面还会有人问得。

**Comment by codefollower** [comment]
我找到合适的办法了，目前在 lealone 里每个 database 都自带两个 schema：public 和 information，我只要让 information 不给应用添加任何东西即可，public 是应用的默认 schema。这样在测试阶段应用不用创建 database 直接用 lealone 这个系统 database 也是安全的。

**Comment by codefollower** [comment]
@qqcbqqkcel 问题已经修复，感谢报告问题。
