### ISSUE TITLE
能否增加使用vertx其他组件的示例

### ISSUE THREAD

**Issue by ContyChen** [lealone/Lealone#164]
能否增加使用vertx其他组件的示例

**Comment by codefollower** [comment]
[lealone-vertx](https://github.com/lealone/Lealone-Plugins/blob/master/service/vertx/pom.xml) 这个插件本身就已经在使用 vertx-web 了，如果你的应用需要用 vertx 的其他组件，直接在应用的 pom.xml 里加上就可以了。

然后可以写一个应用的 Router 继承 org.lealone.plugins.vertx.VertxRouter，就可以初始化 vertx 的其他组件。
可以直接参考 [PetStoreRouter](https://github.com/lealone/Lealone-Examples/blob/main/petstore/petstore-web/src/main/java/org/lealone/examples/petstore/web/PetStoreRouter.java)

**Comment by codefollower** [comment]
最快速的办法就是用 lealone 脚手架创建一个微服务应用，参考[这里](http://lealone.org/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8Lealone%E8%84%9A%E6%89%8B%E6%9E%B6%E5%88%9B%E5%BB%BA%E5%BE%AE%E6%9C%8D%E5%8A%A1%E5%BA%94%E7%94%A8.html)
比如创建了一个 hello 应用，把这个用 maven 管理的项目的代码直接导入到 eclipse 或 idea 中，
然后在 hello-web 那个模块的 pom.xml 中加入 vertx 的其他组件的依赖，
最后在 org.lealone.examples.hello.web.HelloRouter 类的 init 方法中初始化 vertx 的其他组件即可。
