### ISSUE TITLE
之前我记得有提到用一个jar包是可以创建项目脚手架，现在那个jar包跟文档好像都没看到了。望指路

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone#167]

**Comment by codefollower** [comment]
[看这里](http://lealone.org/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8Lealone%E8%84%9A%E6%89%8B%E6%9E%B6%E5%88%9B%E5%BB%BA%E5%BE%AE%E6%9C%8D%E5%8A%A1%E5%BA%94%E7%94%A8.html)
