### ISSUE TITLE
最新5.1.2版本我源码编译了缓存到本地仓库了，可是我还是跑项目还是报错

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone#170]
![image](https://user-images.githubusercontent.com/48706279/226087249-67057f04-9f21-4a19-b8d0-9b0ba513178f.png)
，这个leatone-service.jar包是在哪里构建？

**Comment by codefollower** [comment]
lealone-service 包在 lealone plugins 项目里，应用里找不到包，估计又是阿里云的仓库没有同步更新 maven 的仓库，我已经传到 maven 仓库了。

**Comment by zoujiegogogo** [comment]
收到，谢谢
