### ISSUE TITLE
Lealone元数据中有没有记录数据库对象的创建、修改时间

### ISSUE THREAD

**Issue by ContyChen** [lealone/Lealone#178]
Lealone元数据表中有没有记录数据库对象的创建、修改时间？
或者可以通过什么方式获取到创建修改时间

**Comment by codefollower** [comment]
information_schema.db_objects 记录了每个数据库中的所有对象。

information_schema.table_alter_history 记录了每张表表结构的修改记录。

两张表的字段都没有创建时间、修改时间，目前用不到。

**Comment by ContyChen** [comment]
好的明白
