### ISSUE TITLE
如何创建两个字段联合的唯一索引, 是不是不支持

### ISSUE THREAD

**Issue by zhoujin7** [lealone/Lealone#184]
或者有什么办法保证两个字段联合的唯一性 除了联合主键

**Comment by codefollower** [comment]
```sql
CREATE TABLE IF NOT EXISTS index_test (f1 int, f2 int, f3 varchar);

CREATE UNIQUE INDEX IF NOT EXISTS index_test_uidx1 ON index_test (f2, f3);
```

**Comment by zhoujin7** [comment]
https://github.com/lealone/Lealone/blob/7d98207cf040deac07a6409e753721017d015d28/lealone-db/src/main/resources/org/lealone/common/resources/help.csv
这个是帮助文件
