### ISSUE TITLE
我给alibaba druid提交了对leanlone的支持, 但是一直没有被合并. 不知道是为什么.

### ISSUE THREAD

**Issue by zhoujin7** [lealone/Lealone#185]
我给alibaba druid提交了对leanlone的支持, 但是一直没有被合并. 不知道是为什么.
其实我不懂这些代码, 只是照葫芦画瓢, 根据之前的h2相关代码加上了lealone的代码.
https://github.com/alibaba/druid/pull/5285

**Comment by codefollower** [comment]
alibaba druid 支持不同的数据库没有提供插件的扩展方式吗？我看了一下你的 PR，要修改 druid 的一些类的，这种方式确实不太好。最好有扩展插件，就像 lealone 为了支持 mysql 和 postgresql，就是通过插件的方式进行的。

**Comment by qqcbqqkcel** [comment]
用了 lealone 不需要连接池了啊

**Comment by qqcbqqkcel** [comment]
之前我用 druid 是为了能打印可执行的sql日志方便调试，不知道 lealone 有没有这个功能

**Comment by codefollower** [comment]
> 之前我用 druid 是为了能打印可执行的sql日志方便调试，不知道 lealone 有没有这个功能

在 jdbc url 中加 TRACE_LEVEL_SYSTEM_OUT 或 TRACE_LEVEL_FILE 可以打印调用的 api 和 sql.

两个参数的取值在 org.lealone.common.trace.TraceSystem
    public static final int ERROR = 1;
    public static final int INFO = 2;
    public static final int DEBUG = 3;

**Comment by codefollower** [comment]
> 之前我用 druid 是为了能打印可执行的sql日志方便调试，不知道 lealone 有没有这个功能

在 jdbc url 中加 TRACE_LEVEL_SYSTEM_OUT 或 TRACE_LEVEL_FILE 可以打印调用的 api 和 sql.

两个参数的取值在 org.lealone.common.trace.TraceSystem
    public static final int ERROR = 1;
    public static final int INFO = 2;
    public static final int DEBUG = 3;

**Comment by codefollower** [comment]
实现 JdbcStatement.executeUpdate(String)  方法的调用链路就几步，所以一般 jdbc 驱动都不会直接依赖 log4j 这种日志库。

**Comment by codefollower** [comment]
实现 JdbcStatement.executeUpdate(String)  方法的调用链路就几步，所以 jdbc 驱动一般不会直接依赖 log4j 这种日志库。

**Comment by codefollower** [comment]
实现 JdbcStatement.executeUpdate(String)  方法的调用链路就几步，所以 jdbc 驱动一般不会直接依赖 log4j 这种日志库。

**Comment by qqcbqqkcel** [comment]
```log
/*SQL */SET TRACE_LEVEL_SYSTEM_OUT '2';
2023-06-14 16:16:22 jdbc: 
/**/Connection conn8 = DriverManager.getConnection("jdbc:lealone:tcp://localhost/zhdc_pa", "ROOT", "");
2023-06-14 16:16:22 database: 
/*SQL #:1*/SELECT COUNT(*) AS `total` FROM `Project`;
2023-06-14 16:16:22 database: 
/*SQL #:1*/CALL DATABASE();
2023-06-14 16:16:22 database: 
/*SQL #:20*/SELECT * FROM `Project` LIMIT 10, 10;
2023-06-14 16:16:22 database: 
/*SQL */COMMIT;
2023-06-14 16:16:22 database: 
/*SQL */COMMIT;
2023-06-14 16:16:22 database: disconnected session #9
```

lealone不需要连接池。但是集成 SpringBoot 每次查询都重新获取 Connection 了是正常的吗
