### ISSUE TITLE
The file is locked

### ISSUE THREAD

**Issue by cbqqkcel** [lealone/Lealone#186]
<img width="1391" alt="95d4296ec9f3a5df6f22bd30857e5fd" src="https://github.com/lealone/Lealone/assets/4516585/95619140-7724-43ff-b872-e19c93698835">

开启事务之后，程序跑起来我强制停了一次，就这样了

这个是不是操作的问题。应该怎么处理

**Comment by codefollower** [comment]
确认一下进程有没有杀死

**Comment by qqcbqqkcel** [comment]
目前是把数据全部删除了重新来了一遍，下次遇到再看看

**Comment by codefollower** [comment]
出现那个异常就是还有进程在锁住文件，进程还没有杀死。
