### ISSUE TITLE
backup to xxx.zip 恢复时需要停止数据库吗

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#191]
全量恢复时
我的想法是恢复前执行命令，数据库不在接受任何请求
解压恢复完后执行命令，数据库正常工作。

**Comment by codefollower** [comment]
如果数据库都没停止，说明数据库没有崩溃啊，所以不需要恢复。恢复是在启动数据库的时候做，数据库运行时是不存在恢复的说法的。
