### ISSUE TITLE
[chat] QQ 居然也在用 9210 端口

### ISSUE THREAD

**Issue by forifido** [lealone/Lealone#203]
启动服务发现端口被占用, 原来是 QQ  😂
![2023-10-13_17-21](https://github.com/lealone/Lealone/assets/49850665/71cac2ea-a433-465a-a291-d67aebfa3adb)

**Comment by codefollower** [comment]
可以在命令行中用 -port 指定新的端口，或者在 lealone.yaml 配置文件中修改 port 参数。
