### ISSUE TITLE
请问现在是生产环境可用的状态吗？

### ISSUE THREAD

**Issue by kran** [lealone/Lealone#214]
其实已经关注好多年了，但一直没信心用在生产环境，大佬是否可以对照功能列表出一份状态进度文档呢，尤其是新出的mongodb兼容，好有吸引力，想用起来。

另外，没有看到全文检索相关的文档和代码，若投入使用，像h2那样通过trigger的方式实现一个是否合适？

谢谢，望回复。

**Comment by codefollower** [comment]
lealone 5.2.1 是一个稳定版本，可以用于生产环境。

lealone 6.0.0 还在活跃开发中，不能用于生产环境，mongodb 插件是基于 6.0.0 的，所以也不能用于生产环境。6.0.0 这个版本的研发目前还不到3个月，预计还需要3个月才能稳定。mongodb 插件目前只兼容大半的 mongodb api，稳定发布后会列出不支持的 api。

全文检索功能早期的版本是直接使用 h2 的功能，后来我把它删除了，后续会通过插件的方式支持。

**Comment by kran** [comment]
@codefollower 我目前在使用h2，因为遇到了几次数据库文件损坏，也找不到原因，所以想换一个，对比h2，lealone的稳定性上有没有优势？如果稳定性上没问题，就只有全文检索需要做一下就能完全替代了。

**Comment by codefollower** [comment]
不敢绝对说没有 bug 的，所以稳定性这个问题不好比较，h2 每次发布新版本 changelog 中确实修复了很多 bug，而 lealone 的用户数目前肯定没有 h2 多，所以发现的 bug 少。

lealone 虽然在11年前是从 h2 起步的，但早都分道扬镳了，90%都是不同的，lealone 单机版的优势主要是并发控制。

**Comment by codefollower** [comment]
Lealone 的全文检索插件我重新放出来了，在这里: https://github.com/lealone-plugins/lealone-fulltext
还没细测，可能还有 bug。

**Comment by kran** [comment]
@codefollower 感谢，我会在接下来的项目里用lealone，只要数据文件不坏就不是大问题。

**Comment by codefollower** [comment]
lealone 5.2.1 已经高并发压测过了，目前没有发现数据文件损坏问题。
使用 lealone 在上线前你也可以用你的真实数据压测一下，如果遇到数据文件损坏问题，发出来，我会尽快修复的。

**Comment by kran** [comment]
好的，一定会测一测的。我还在想把h2的测试用例拿过来的成本高不高

**Comment by codefollower** [comment]
h2 最新版本的一些新语法 lealone 是不支持的，用 h2 的 jdbc 驱动也无法连 lealone，如果你使用的是标准的 jdbc api，用 lealone 的  jdbc 驱动替换 h2 的 jdbc 驱动，基本上95%以上的测试都能正常跑的。

**Comment by kran** [comment]
> h2 最新版本的一些新语法 lealone 是不支持的，用 h2 的 jdbc 驱动也无法连 lealone，如果你使用的是标准的 jdbc api，用 lealone 的 jdbc 驱动替换 h2 的 jdbc 驱动，基本上95%以上的测试都能正常跑的。

那太好了，我尝试一下
