### ISSUE TITLE
 嵌入式模式下批量更新会卡住

### ISSUE THREAD

**Issue by cbqqkcel** [lealone/Lealone#239]
![image](https://github.com/user-attachments/assets/994d5902-1dba-48cb-a583-0e9cc3e81fa7)

ac.get(this) 这里会卡住
在嵌入式模式下是不是不能多线程执行sql，我这个项目没有tomcat是定时任务触发的数据更新

**Comment by codefollower** [comment]
我排查一下原因，可能是个 bug

**Comment by codefollower** [comment]
bug 已经修复，感谢报告问题

**Comment by codefollower** [comment]
lealone 6 嵌入模式已经可以安全使用多线程了，如果遇到任何并发问题，说明存在一个之前没有发现的 bug。
