### ISSUE TITLE
LocalDateTime 值变成 aced00057372000d

### ISSUE THREAD

**Issue by cbqqkcel** [lealone/Lealone#240]
![image](https://github.com/user-attachments/assets/bfa94d1d-9db4-4052-835f-265495d89060)

![image](https://github.com/user-attachments/assets/373201a6-6a47-4043-899c-40c507fe1404)

如果我注释调 .updatedAt(now) 这行代码就能更新成功。

**Comment by cbqqkcel** [comment]
用SQL 管理工具可以查询出来数据，日期是正常的。在代码里面就是null 是不是我的  orm 框架不支持。mysql 的是可以查出来的

**Comment by cbqqkcel** [comment]
![image](https://github.com/user-attachments/assets/ca82a5f9-7d10-4f78-8fe2-9af2974da3b9)
newRow 里面的值还是正常的

**Comment by cbqqkcel** [comment]
![image](https://github.com/user-attachments/assets/5c20ab5c-6b56-45fd-acfa-d8169e59f522)
嵌入式下可以可以使用同步吗，由于是异步我无法从mybatis中debug过来

**Comment by cbqqkcel** [comment]
DataType.convertToValue 不支持  LocalDateTime

**Comment by cbqqkcel** [comment]
![image](https://github.com/user-attachments/assets/2120babb-e1e0-470e-9c0a-7082bdfdb0bf)

JdbcPreparedStatement 不知道LocalDateTime

LocalDateTimeTypeHandler 是直接调用 ps.setObject 了，最后到DataType.convertToValue 中是不支持LocalDateTime  的

**Comment by codefollower** [comment]
java.time 包中的日期时间还不支持，所以转换时会有问题。

**Comment by cbqqkcel** [comment]
如果要支持的话还得支持 LocalDateTime LocalDate LocalTime 这几个。
1.8 后不推荐使用 java.util.Date 了。

**Comment by codefollower** [comment]
> ![image](https://private-user-images.githubusercontent.com/4516585/369633070-5c20ab5c-6b56-45fd-acfa-d8169e59f522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzYzMDEsIm5iZiI6MTcyNjkzNjAwMSwicGF0aCI6Ii80NTE2NTg1LzM2OTYzMzA3MC01YzIwYWI1Yy02YjU2LTQ1ZmQtYWNmYS1kODE2OWU1OWY1MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTYyNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmZmZDQ2ODI3Zjg0MDY4NTVkZjQ0YmY2OGQwY2EzNDc0ZmQyNWI1ZTBmZmRiNTVjOTI3NjEzZDNjMWJhNmU2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.a-7O2kqeZ_qRu6K4hkhh9ksQLPJ7UwkF1PKG4eBXAOo) 嵌入式下可以可以使用同步吗，由于是异步我无法从mybatis中debug过来

嵌入模式下真正执行 sql 语句的线程是 EScheduleService 线程，mybatis 的线程调用到 jdbc 的 api 时，只是把 sql 提交给EScheduleService 线程执行，所以无法在 mybatis 的线程里一路 debug 所有代码的。

**Comment by codefollower** [comment]
> 如果要支持的话还得支持 LocalDateTime LocalDate LocalTime 这几个。 1.8 后不推荐使用 java.util.Date 了。

下一个小版本再看看如何支持 java.time 包中的日期时间，H2 数据库确实支持挺长一段时间了

**Comment by codefollower** [comment]
不管是嵌入模式还是 client-server 模式，lealone 的内核代码都是由 lealone 内部的调度服务线程执行，外部线程无法也不给执行内核代码。

**Comment by codefollower** [comment]
Lealone 的 JDBC 客户端已经支持 LocalDate、LocalTime、LocalDateTime，其他 java.time 类型还不支持。

通过 setObject/getObject 来使用，具体用法可以参考 [JSR310JavaTimeTest](https://github.com/lealone/Lealone/blob/master/lealone-test/src/test/java/com/lealone/test/client/JSR310JavaTimeTest.java)
