### ISSUE TITLE
899和915 JAVA_OBJECT和ARAAY好像永远不会执行

### ISSUE THREAD

**Issue by cbqqkcel** [lealone/Lealone#241]
https://github.com/lealone/Lealone/blob/20492a40688b0514f0b51579671c17cb160e1ca9/lealone-common/src/main/java/com/lealone/db/value/Value.java#L915C1-L916C1

上面已经判断过来，这里永远不会执行。

**Comment by codefollower** [comment]
com.lealone.db.value.Value.convertTo(int) 方法过于复杂，Value 有多少种类型需要两两转换的就有n*n种，在第一个 switch 中如果不能 return，就统一把当前 value 转成 String，然后再把 String 转成 targetType，所以第二个 switch 是压箱底，会把 String 可能会转的 n 种 Value 类型都列出来了，用不到也问题不大，只是为了完整。

这些都是 H2 的遗留代码

**Comment by codefollower** [comment]
还是得重构一下这些遗留代码，可读性太差，switch 太长
