### ISSUE TITLE
DBeaver 无法连接 Lealone 数据库

### ISSUE THREAD

**Issue by lovefishs** [lealone/Lealone#248]
Lealone 版本: 6.0.1
DBeaver 版本: 24.2.0.202409011551
系统: macOS 13.6.9

Lealone 已经本地启动

```
Lealone version: 6.0.1
Use default config
Base dir: /Users/xxx/yyy/lealone/lealone_data
Init storage engines: 20 ms
Init transaction engines: 102 ms
Init sql engines: 7 ms
Init protocol server engines: 23 ms
Init lealone database: 244 ms
TcpServer started, host: 127.0.0.1, port: 9211
Total time: 455 ms (Load config: 3 ms, Init: 432 ms, Start: 20 ms)
Exit with Ctrl+C
```

当使用 DBeaver 连接 Lealone 时，会打印错误日志，如下

```
Failed to read remote address[127.0.0.1:54043]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
Failed to read remote address[127.0.0.1:54187]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
Failed to read remote address[127.0.0.1:54333]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
```

连接 Lealone 客户端成功

```
Welcome to Lealone Shell 6.0.1
Connect to jdbc:lealone:tcp://localhost:9211/lealone
Commands are case insensitive; SQL statements end with ';'
help or ?          Display this help
list               Toggle result list / stack trace mode
maxwidth or md     Set maximum column width (default is 100)
autocommit or ac   Enable or disable autocommit
history or h       Show the last 20 statements
reconnect or rc    Reconnect the database
quit or exit       Close the connection and exit

sql>
```

Lealone 驱动器已经根据文档正确创建

连接报错信息如下

```
Can't create driver instance (class 'com.lealone.client.jdbc.JdbcDriver

').
  Error creating driver 'Lealone' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver

'
  Error creating driver 'Lealone' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver

'
    com.lealone.client.jdbc.JdbcDriver


    com.lealone.client.jdbc.JdbcDriver
```

**Comment by codefollower** [comment]
> 当使用 DBeaver 连接 Lealone 时，会打印错误日志，如下
> 
> ```
> Failed to read remote address[127.0.0.1:54043]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> Failed to read remote address[127.0.0.1:54187]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> Failed to read remote address[127.0.0.1:54333]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> ```

这个 WARN 是你的电脑上开了 QQ，它会连到9210端口，然后给9210端口发信息。

**Comment by codefollower** [comment]
> 连接报错信息如下
> 
> ```
> Can't create driver instance (class 'com.lealone.client.jdbc.JdbcDriver
> 
> ').
>   Error creating driver 'Lealone' instance.
> Most likely required jar files are missing.
> You should configure jars in driver settings.
> 
> Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> 
> '
>   Error creating driver 'Lealone' instance.
> Most likely required jar files are missing.
> You should configure jars in driver settings.
> 
> Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> 
> '
>     com.lealone.client.jdbc.JdbcDriver
> 
> 
>     com.lealone.client.jdbc.JdbcDriver
> ```

这个是配置驱动的时候没有把 lealone-6.0.1.jar 加进去，参考 [使用DBeaver访问Lealone数据库](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8DBeaver%E8%AE%BF%E9%97%AELealone%E6%95%B0%E6%8D%AE%E5%BA%93.md) 中的第二张截图。

**Comment by lovefishs** [comment]
> > 当使用 DBeaver 连接 Lealone 时，会打印错误日志，如下
> > ```
> > Failed to read remote address[127.0.0.1:54043]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > Failed to read remote address[127.0.0.1:54187]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > Failed to read remote address[127.0.0.1:54333]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > ```
> 
> 这个 WARN 是你的电脑上开了 QQ，它会连到9210端口，然后给9210端口发信息。

我启动数据库的时候，使用了 `-port` 参数修改了端口为 `9211`，怎么会还往 `9210` 发信息呢？

**Comment by lovefishs** [comment]
> > 连接报错信息如下
> > ```
> > Can't create driver instance (class 'com.lealone.client.jdbc.JdbcDriver
> > 
> > ').
> >   Error creating driver 'Lealone' instance.
> > Most likely required jar files are missing.
> > You should configure jars in driver settings.
> > 
> > Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> > 
> > '
> >   Error creating driver 'Lealone' instance.
> > Most likely required jar files are missing.
> > You should configure jars in driver settings.
> > 
> > Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> > 
> > '
> >     com.lealone.client.jdbc.JdbcDriver
> > 
> > 
> >     com.lealone.client.jdbc.JdbcDriver
> > ```
> 
> 这个是配置驱动的时候没有把 lealone-6.0.1.jar 加进去，参考 [使用DBeaver访问Lealone数据库](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8DBeaver%E8%AE%BF%E9%97%AELealone%E6%95%B0%E6%8D%AE%E5%BA%93.md) 中的第二张截图。

我是按照文档进行配置的，具体信息见下面截图

<img width="700" alt="1" src="https://github.com/user-attachments/assets/52a989a9-6c21-4663-8e54-643e2bf27bc0">
<img width="700" alt="2" src="https://github.com/user-attachments/assets/58a8391c-b273-40de-8f51-bee3886270bf">
<img width="700" alt="3" src="https://github.com/user-attachments/assets/6e460f42-6c45-4d96-acd3-7f09e8b7d830">
![4](https://github.com/user-attachments/assets/f26854b3-c239-4bb3-96e2-284adf24d945)

**Comment by codefollower** [comment]
> > 当使用 DBeaver 连接 Lealone 时，会打印错误日志，如下
> > ```
> > Failed to read remote address[127.0.0.1:54043]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > Failed to read remote address[127.0.0.1:54187]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > Failed to read remote address[127.0.0.1:54333]: Packet too large, maxPacketSize: 16777216, receive: 1195725856
> > ```
> 
> 这个 WARN 是你的电脑上开了 QQ，它会连到9210端口，然后给9210端口发信息。

9211端口QQ也会发

**Comment by codefollower** [comment]
> > > 连接报错信息如下
> > > ```
> > > Can't create driver instance (class 'com.lealone.client.jdbc.JdbcDriver
> > > 
> > > ').
> > >   Error creating driver 'Lealone' instance.
> > > Most likely required jar files are missing.
> > > You should configure jars in driver settings.
> > > 
> > > Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> > > 
> > > '
> > >   Error creating driver 'Lealone' instance.
> > > Most likely required jar files are missing.
> > > You should configure jars in driver settings.
> > > 
> > > Reason: can't load driver class 'com.lealone.client.jdbc.JdbcDriver
> > > 
> > > '
> > >     com.lealone.client.jdbc.JdbcDriver
> > > 
> > > 
> > >     com.lealone.client.jdbc.JdbcDriver
> > > ```
> > 
> > 
> > 这个是配置驱动的时候没有把 lealone-6.0.1.jar 加进去，参考 [使用DBeaver访问Lealone数据库](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8DBeaver%E8%AE%BF%E9%97%AELealone%E6%95%B0%E6%8D%AE%E5%BA%93.md) 中的第二张截图。
> 
> 我是按照文档进行配置的，具体信息见下面截图
> 
> <img alt="1" width="700" src="https://private-user-images.githubusercontent.com/1687242/384748681-52a989a9-6c21-4663-8e54-643e2bf27bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTQyMDEsIm5iZiI6MTczMTI5MzkwMSwicGF0aCI6Ii8xNjg3MjQyLzM4NDc0ODY4MS01MmE5ODlhOS02YzIxLTQ2NjMtOGU1NC02NDNlMmJmMjdiYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDI1ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVlMTE2ZjE5YjVmNGIxMjgwMzUzMzkwOTdmOTUwMzMxZGI3NDlmM2FmYTA3ZmYwNzVjOTNlM2U5OGMxZjNmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g7ROwD8HUVCiJzX7E4AxrRbEm6g9SAOOHiuijIyxY84"> <img alt="2" width="700" src="https://private-user-images.githubusercontent.com/1687242/384748701-58a8391c-b273-40de-8f51-bee3886270bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTQyMDEsIm5iZiI6MTczMTI5MzkwMSwicGF0aCI6Ii8xNjg3MjQyLzM4NDc0ODcwMS01OGE4MzkxYy1iMjczLTQwZGUtOGY1MS1iZWUzODg2MjcwYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDI1ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgyY2ViMzcyZDYyYzRmMTg0MmI3ODUyMThiYjU4M2FjZTNlNDNhZjJhYjI0ZmVjYjg3ZmQ3NThlZTRhMWZjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BPEAuiMJWDnmzKon_tJheqbC5_gImmtE4ydZ3Q6_B_A"> <img alt="3" width="700" src="https://private-user-images.githubusercontent.com/1687242/384748695-6e460f42-6c45-4d96-acd3-7f09e8b7d830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTQyMDEsIm5iZiI6MTczMTI5MzkwMSwicGF0aCI6Ii8xNjg3MjQyLzM4NDc0ODY5NS02ZTQ2MGY0Mi02YzQ1LTRkOTYtYWNkMy03ZjA5ZThiN2Q4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDI1ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgxMTk0YmEyMzRkOTVhMzlhN2I2YzgxY2Y4MzBjZGE4N2UwOWU1MmVlOWEwMTc4MThmOTk4ZjFkODM1Mzc2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nTHBt6OCT_kOU3_oyZAYxOBpsWHm40xuLfm2yOrAaIY">

你截图里的端口号配成9210了，应该是9211
找不到 JdbcDriver 类也可能是 DBeaver 需要重启动，lealone-6.0.1.jar 包里是有 JdbcDriver 这个类的，而且你加 jar 包的那个截图都能实别出 com.lealone.client.jdbc.JdbcDriver 了，若是还找不到，看看你第一张截图配置的类名后面是不是多加了空格，有了空格 DBeaver 也没法识别。

**Comment by codefollower** [comment]
你截图里的端口号配成9210了，应该是9211 找不到 JdbcDriver 类也可能是 DBeaver 需要重启动，lealone-6.0.1.jar 包里是有 JdbcDriver 这个类的，而且你加 jar 包的那个截图都能实别出 com.lealone.client.jdbc.JdbcDriver 了，若是还找不到，看看你第一张截图配置的类名后面是不是多加了空格，有了空格 DBeaver 也没法识别。
