### ISSUE TITLE
关于故障处理

### ISSUE THREAD

**Issue by Leviathan1995** [lealone/Lealone#77]
我想问一下，如果单个节点出现故障，你是如何判断是什么故障的？比如网络，io

**Comment by codefollower** [comment]
数据库通常都有错误类型分类的，Lealone定义了很多ErrorCode，基本上每种异常都会有ErrorCode，
节点故障要看这异常能不能发回来，能发回来自然是知道故障类型的。

节点联系不上，并不是通过简单的心跳包检测，而是使用类似Cassandra的方式: The Phi Accrual Failure Detector.

另外，这里开源的Lealone只是单机版的数据库，不包含分布式的，分布式存储是在另一个不开源的AOSE存储引擎中，里面就是用了The Phi Accrual Failure Detector. 特别适合处理闪断问题。

**Comment by Leviathan1995** [comment]
明白了明白了。方便留下QQ吗？我自己想写一个分布式的键值数据库，有几个架构上的问题向问问你。

**Comment by codefollower** [comment]
sorry，这里不是用来做技术咨询的，GitHub Issues只用来管理与Lealone相关的问题。
AOSE存储引擎目前是商业软件，也不会在这里探讨具体的技术实现细节。

**Comment by Leviathan1995** [comment]
谢谢。
