### ISSUE TITLE
请问有没有计划支持leveldb的存储引擎

### ISSUE THREAD

**Issue by tixo** [lealone/Lealone#78]
请问有没有计划支持leveldb的存储引擎？

**Comment by codefollower** [comment]
没有计划，官方支持的存储引擎只有单机版的MVStore: http://www.h2database.com/html/mvstore.html
以及一个内部未开源的商业存储引擎，叫: AOSE，同时支持单机和分布式版本。

Lealone的早期版本支持WiredTiger存储引擎: https://github.com/wiredtiger/wiredtiger
然后我们还是觉得自己开发AOSE存储引擎更有优势，
所以，现在第三方的存储引擎，只支持MVStore
其他存储引擎的支持，感兴趣的人可以自己集成进来。

这里有一个MemoryStorageEngine的完整例子
https://github.com/lealone/Lealone/tree/master/lealone-common/src/main/java/org/lealone/storage/memory

打成jar包时，增加一个META-INF/services/org.lealone.storage.StorageEngine文件，
里面放第三方的StorageEngine类名，
就能自动集成到Lealone中了。

**Comment by tixo** [comment]
请问有没有一些AOSE的技术资料可供分享的

**Comment by codefollower** [comment]
没有，AOSE不开源，技术文档目前也没有对外提供。

**Comment by tixo** [comment]
谢谢回复，这个issue
