### ISSUE TITLE
能指点下怎么调试Lealone中client-server模式的代码吗？

### ISSUE THREAD

**Issue by lmsreborn** [lealone/Lealone#79]
Shell.java启动后，输入sql语句，但是不知道TcpServer监听到后，如何处理，如何和SQLEngine交互？我尝试用debug模式启动Lealone.java，但是必须运行完，shell才有反应，显示一些帮助信息和“sql>"。TcpServer.java中，不知道怎么设置断点调试了......

**Comment by codefollower** [comment]
因为已经异步化了，不再像早期那样一个线程对应一个连接(或session)

可以在TcpServer的
server.connectHandler(socket ->
里先打断点，每进来一个新的连接会在这里暂停;

然后可以在org.lealone.net.AsyncConnection.handle(Buffer)里打断点，
这里是处理协议包的;

org.lealone.net.CommandHandler.run()处理每条sql。

**Comment by lmsreborn** [comment]
我现在对于select * from test; 这样的查询语句，追踪到了org.lealone.client.ClientCommand.java : 259(第259行) Result result = ac.getResult(); 然后到org.lealone.net.AsyncCallback.java:66 latch.await(); 

之前不知怎么搞的，将vert.x的thread给blocked了，vert.x对应的检查器报错，然后到latch.await()那一步后，lealone.java下居然能单步调试了，然后就跳转到org.lealone.net.AsyncConnection.handle(Buffer)里面的断点了，继而后面可以看到server那端是如何执行的了（记得调了三次request，对应query, result_close, command_close）

现在的问题是，我重启后，vert.x正常运作后线程不再阻塞, 然后执行到latch.await()后，不再跳转，直接蹦出结果了，Lealone.java下无法像之前那样单步调试了（Lealone.java和Shell.java都开了debug模式）.......

**Comment by codefollower** [comment]
Lealone.java就是启动类啊，启动完了，main线程就退出了，自然就不能再单步调试了

怎么理解Lealone代码实现原理的问题不讨论了。
GitHub的issues不是用来干这些事的。
