### ISSUE TITLE
你好 我用use database命令切换不了数据库是什么原因？谢谢

### ISSUE THREAD

**Issue by yh3434** [lealone/Lealone#80]
sql> show databases;
DATABASE_NAME
TEST
lealone
MYDB
(3 rows, 52 ms)

sql> use TEST;
Error: org.lealone.common.exceptions.JdbcSQLException: General error: "org.lealone.common.exceptions.LealoneException: org.lealone.common.exceptions.DbException: [Server] Schema ""TEST"" not found; SQL statement:
use TEST [90079-0]" [50000-0]

**Comment by codefollower** [comment]
Lealone跟MySQL不一样
在MySQL里，database和schema是同一个东西，而Lealone不是

所以show databases和show schemas会得到不同的结果
use命令只能用来切换当前数据库下的某个schema。

每个RDBMS的数据库对象模型都会有差异的，
Lealone的数据库对象模型跟H2和PostgreSQL类似。

**Comment by yh3434** [comment]
好的，谢谢。
