### ISSUE TITLE
可以商用吗。

### ISSUE THREAD

**Issue by qqcbqqkcel** [lealone/Lealone#83]
现在可以商用吗，不重要的那种系统。

**Comment by codefollower** [comment]
等GA版吧，现在还很不稳定，还在加一些功能，等做完下面链接中提到的功能应该就接近GA了。
[技术想法分享](https://github.com/codefollower/My-Blog/issues/22)
其中１、２、３、５都已经完成，６正在做，４也已经成型，但需要做完６后再进一步优化。
感谢关注。

**Comment by codefollower** [comment]
Lealone的代码从10月16号以后就没更新了，最近身体不太好，都在休养。
下个月应该就会重新投入工作了。
最近一周在知乎说点技术，没东西可看的话，到上面可以看看
这里是我的知乎账号链接: [codefollower](https://www.zhihu.com/people/codefollower/)

**Comment by Longda-Feng** [comment]
你的现在1/2/3/4/5/6 想法完成了吗？

**Comment by codefollower** [comment]
@Longda-Feng
[我的Lealone数据库后续开发不开源了](https://zhuanlan.zhihu.com/p/57784121)
