### ISSUE TITLE
一些问题请教一下？

### ISSUE THREAD

**Issue by Longda-Feng** [lealone/Lealone#86]
问题稍微有点多，

我是一家创业公司， 想用一个内嵌的数据库， 正在选型 h2 和lealone？

（1） 截止 2019-3-19， lealone 和最新版的h2 有什么区别？或者lealone 比h2 有什么优势？

（2）我看过你有一个milestone， 介绍lealone 有5代， 当前版本是第5代吗？我看你的relase 是写的5.0， 貌似和你的介绍不一样。
你的介绍里面， 第一代，就是h2 + hbase, 第二代， sql-engine + cassendra， 第三代 sharding推到存储引擎， 用了leaf-page-sharding算法，分布式事务， 全链路异步化，sql 抢占 ，第四代， 号称自治数据库， 消除sharding，单机， replica-set （其实第4代还是没有明白）？

（3）如果我用你的lealone， 你会不会同步一下最新的h2， 如果不会， 那你的lealone 是主体是基于什么版本呢？如果打算同步， 你大概什么时候，可以完成同步最新的h2？

我邮箱 hustjackie@outlook.com， 不知道，你方不方便留个邮箱给我。

**Comment by codefollower** [comment]
毫无疑问，你得选h2，lealone还不稳定不成熟，若只是单纯的用一个内嵌数据库，h2也更轻量。

lealone虽然最初是从h2演变而来的，但是现在跟h2差别巨大了，
我已经连续至少３年没有把h2新加的功能移到lealone中了，同样lealone中新加的功能更不可能移到h2中，因为现在h2和lealone真的是两个没多少共同点的数据库了。
