### ISSUE TITLE
Lealone分布式部署文档？

### ISSUE THREAD

**Issue by xiatiansong** [lealone/Lealone#87]
有时间能在文档中提供分布式部署相关的说明么？希望可以在分布式环境进行测试

**Comment by codefollower** [comment]
因为分布式部署需要分布式事务支持的，而分布式事务的实现是没有开源的，所以即使我写了文档了也是不完整的。有一个分布式事务和副本一致性协议相关的模块没有开源，我内部自己测试时会结合这个模块和这里的测试代码一起测：https://github.com/lealone/Lealone/tree/master/lealone-test/src/test/java/org/lealone/test/start/one_data_center
里面的测试类启动一个就代表启动一个节点了。虽然缺少一个模块这些测试类也可以跑，但是如果事务发生失败时没有那个模块就会造成数据不一致。

原本是打算做一个基于2pc和raft的免费模块的，一直抽不出时间做。

**Comment by codefollower** [comment]
@xiatiansong 
如果你像我一样在windows上面开发，可以先把lealone的代码弄到你本机上，
然后在cmd窗口中切换到lealone的源代码根目录，执行 build -p 可以打包构建lealone的分发包，
执行完后，可以cd到target\lealone-5.0.0-SNAPSHOT\bin目录，然后运行 lealone -nodes 3 就可以启动一个3节点的伪分布式集群了。

**Comment by codefollower** [comment]
目前分布式事务和复制协议的实现都已经开源了，
相关部署文档可以参考这篇文档: [运行模式快速入门](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E8%BF%90%E8%A1%8C%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.md)
