### ISSUE TITLE
运行项目，执行sql异常

### ISSUE THREAD

**Issue by Joe192168** [lealone/Lealone#91]
Welcome to Lealone Shell 5.0.0
Exit with Ctrl+C
[Enter]   jdbc:lealone:tcp://127.0.0.1:7210/lealone
URL
[Enter]   root
User
[Enter]   Hide
Password
Connected
Commands are case insensitive; SQL statements end with ';'
help or ?      Display this help
list           Toggle result list / stack trace mode
maxwidth       Set maximum column width (default is 100)
autocommit     Enable or disable autocommit
history        Show the last 20 statements
quit or exit   Close the connection and exit

sql> CREATE TABLE IF NOT EXISTS test (f1 int primary key, f2 long);
(Update count: 0, 14 ms)

sql> INSERT INTO test(f1, f2) VALUES(3, 2);
(Update count: 1, 3 ms)

sql> SELECT * FROM test;
Error: General error: "java.lang.NullPointerException" [50000-0]
sql>

**Comment by codefollower** [comment]
@Joe192168 你更新一下刚提交的代码，现在可以了
https://github.com/lealone/Lealone/commit/f90c329d65a6ccd4fce5dad2367d6c99452b803e

最近代码提交比较频繁，这个NPE问题是昨天的修改引入的 https://github.com/lealone/Lealone/commit/7270621de64d6c1a6ed3795c1896d0e41b98656a

**Comment by Joe192168** [comment]
ok，试试
