### ISSUE TITLE
如何连接第三方关系型数据库测试？

### ISSUE THREAD

**Issue by Joe192168** [lealone/Lealone#92]
该项目只支持目前主流关系型数据库吗？

**Comment by codefollower** [comment]
Lealone本身就是关系型数据库啊，但是不支持通过Lealone连其他第三方数据库。

**Comment by Joe192168** [comment]
是的，启动Lealone的时候已经看出来，所以确认一下。后续考虑连接其他第三方数据源吗？

**Comment by codefollower** [comment]
Bats那项目可以连不同数据源，Lealone不会考虑的。

**Comment by Joe192168** [comment]
但是Bats项目是侧重OLAP的，我想在OLTP项目中也可以连接第三方数据源操作。
