### ISSUE TITLE
在 intellj idea 中运行测试会卡住

### ISSUE THREAD

**Issue by jiamo** [lealone/Lealone#93]
没有提前运行 tcpserver 只是想跑一遍测试。

具体卡住的是 lealone-test/src/test/java/org/lealone/test/aose/DistributedBTreeMapTest.java 
在 testRemotePage 函数中会卡住在  map.put(1, "abc") 里面。

具体怎么回事没有搞明白。 最后跟踪到的是 

Listener 类的 await 函数。

**Comment by codefollower** [comment]
那个还不稳定，分布式功能是最近加的，修改也比较频繁，我目前并没有提交一次代码就跑完所有测试，所以可能会引起新的bug没有立即修复。建议你目前跑非分布式的测试用例。

**Comment by jiamo** [comment]
不过最好保证有一个分支上是有测试全通过会好一点。

比如这个 测试。我这里好像就有问题 。
lealone-test/src/test/java/org/lealone/test/aote/AMTransactionMapTest.java / testSyncOperations 
中 

        System.out.println( map.get("1"));
        System.out.println( map.get("2"));
        System.out.println( map.get("3"));
        System.out.println( map.get("4"));
        System.out.println( map.get("5"));
        System.out.println( map.get("6"));
        System.out.println( map.size());
        assertEquals(2, map.size());


打印结果是 ：

    null
    b
    null
    null
    null
    g
    3

从 get 来看已经只有 2 个元素了。 但 count 还有 3 个。

**Comment by codefollower** [comment]
是的，aote模块不稳定，你看我最新的提交记录都是aote模块相关的，第一个RC版还是有不少bug的。因为修改比较频繁，我通常只单独跑一个测试，通过了就看下一个问题，集成测试或全量测试并没有做。

目前的RC2依然是同一个分支的，当前只是把原本未开源的分布式事务和复制协议合并到aote里，如果没有分布式事务和复制协议的功能，所有分布式相关的跑起来都不正常的。

**Comment by codefollower** [comment]
AMTransactionMapTest 我也跑不通了，估计最近一次改动出bug了

**Comment by codefollower** [comment]
@jiamo 你是想试玩，还是想要看最新代码，试玩的话先用RC1吧，按 [运行模式快速入门](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E8%BF%90%E8%A1%8C%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.md) 下载压缩包解压试完一下就可以了，
最新的RC2主要是开源分布式事务和复制功能的实现代码(阶段1)，只做到一大半，没有完成，原有的测试用例我还没跑，我只是启动集群后，用ReplicationTest那个测试类做功能开发，所以如果你要紧跟最新代码的话是一定会碰到测试用例跑不通的情况的。

**Comment by codefollower** [comment]
AMTransactionMapTest 的bug我知道原因了，我把[UndoLogRecord](https://github.com/lealone/Lealone/blob/master/lealone-aote/src/main/java/org/lealone/transaction/aote/log/UndoLogRecord.java) 第76到第80注释掉了，删除的记录没有实际删除，所以算size时就多1了。主要是为了实现RepeatableRead，所以存储层返回的size不能是直接的size，还需要去掉被标记为删除的记录。
