### ISSUE TITLE
Lealone存储的数据模型

### ISSUE THREAD

**Issue by GrapeBaBa** [lealone/Lealone#94]
Lealone存储数据的数据，Key中只存储Key，Value中存储的是所有的版本数据链是吗？

**Comment by codefollower** [comment]
AOSE是Lealone的存储引擎，它不会在乎Key和Value里具体是什么东西的，只要提供适合的StorageDataType给它，然后由StorageDataType做序列化和反序列化的操作即可。
里面的BTreeMap类是一个范型类，提供的API类似于java.util.Map，接受各种数据类型。

AOTE是Lealone的事务引擎，AOTE才关心Value里面存的是什么，比如为了实现REPEATABLE_READ，此时的Value就是一个TransactionalValue（事务化的Value），TransactionalValue就是一个数据链。这个数据链只存放当前活跃事务的数据，不包含历史数据，所以Lealone的多版本跟HBase不一样，HBase的多版本是会持久化的。
