### ISSUE TITLE
技术选型疑问

### ISSUE THREAD

**Issue by copyshop** [lealone/Lealone#96]
一个web统计分析的工具（类似百度统计），目前用es做存储，业务码农，无法从各个原理透彻理解大师的产品。
我想请问大师，能否用Lealone替代es。对于这类应用Lealone适不适合。sql能支持avg  group by 带分页的这种，就像mysql一样操作这样简单。

**Comment by codefollower** [comment]
分析类的应用不适合Lealone，Lealone是用于事务处理的。

**Comment by copyshop** [comment]
谢谢,非常感谢。
