### ISSUE TITLE
能否已内嵌模式启动组成cluster模式？加上raft协议确保数据一致性

### ISSUE THREAD

**Issue by chuntaojun** [lealone/Lealone#97]

**Comment by codefollower** [comment]
Lealone的嵌入模式指的是单机并且不需要JDBC客户端的场景。

没有嵌入式集群的说法的，如果你只是想在你的java应用代码中启动Lealone集群这是天然支持的，测试代码里就有启动集群的例子。

最后，Lealone不需要raft，有自己的数据（副本）一致性协议。

**Comment by chuntaojun** [comment]
我说下我的想法：我是希望lealone能够embed模式在我的springboot中启动，但是，我这个应用是可能多实例部署的，为了部署方便，希望数据库能够内嵌的方式启动，然后当应用采用多实例部署时，就涉及到分布式存储一致性的问题了，然后可以说接入外部的一致性协议实现来保证每个节点数据的一致性，等于就是希望能不能成为java的TiDB或者类似这个东西，

**Comment by codefollower** [comment]
可以的，在一台服务器或虚拟机中就可以部署多个Lealone实例，就跟内嵌tomcat一样，只要端口号不同就可以了。

**Comment by chuntaojun** [comment]
> 可以的，在一台服务器或虚拟机中就可以部署多个Lealone实例，就跟内嵌tomcat一样，只要端口号不同就可以了。

我抽空实际测试下
